Repository offen/offen, pull requests merged in 2020-06, with the labels that each got.

#380 Print help on unknown subcommand
  server/cmd/offen/main.go
Labels: feature

#381 Mute logger when trying to serve static assets
  server/router/static.go
Labels: chore

#382 Implement memory based storage backend for scenarios where IndexedDB fails
  vault/src/queries.js
Labels: fix

#385 Alpha Release 8
  .circleci/config.yml
  README.md
  auditorium/index.js
  auditorium/src/middleware/push-state.js
  auditorium/src/views/auditorium-operator.js
  auditorium/src/views/auditorium-user.js
  auditorium/src/views/components/console/change-email.js
  bootstrap.yml
  build/Dockerfile
  docker-compose.yml
  script/index.js
  server/cmd/offen/main.go
  server/config/definition_windows.go
  server/persistence/login.go
  server/persistence/management.go
  server/public/fonts.css
  server/public/index.go.html
  server/router/static.go
  vault/src/api.js
  vault/src/handler.js
  vault/src/middleware.js
  vault/src/queries.js
Labels: release

#388 Adopt REUSE for providing and checking license information
  .circleci/config.yml
  .dockerignore
  .editorconfig
  .github/FUNDING.yml
  .gitignore
  .reuse/dep5
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile.golang
  Dockerfile.node
  LICENSES/Apache-2.0.txt
  LICENSES/MIT.txt
  Makefile
  NOTICE
  README.md
  SECURITY.md
  auditorium/.babelrc
  auditorium/README.md
  auditorium/styles/negative-margins.css
  build/Dockerfile
  build/Dockerfile.build
  docker-compose.integration.yml
  docker-compose.yml
  integration/cypress/integration/assets.spec.js
  integration/cypress/integration/lighthouse.spec.js
  integration/cypress/integration/operator.spec.js
  integration/cypress/plugins/index.js
  integration/cypress/support/commands.js
  integration/cypress/support/index.js
  nginx.conf
  packages/README.md
  script/README.md
  server/Makefile
  server/README.md
  server/bootstrap.yml
  server/extract-strings.sh
  server/public/emails.go.html
  server/public/fonts/roboto-v20-latin-700.ttf.license
  server/public/fonts/roboto-v20-latin-700.woff.license
  server/public/fonts/roboto-v20-latin-700.woff2.license
  server/public/fonts/roboto-v20-latin-regular.ttf.license
  server/public/fonts/roboto-v20-latin-regular.woff.license
  server/public/fonts/roboto-v20-latin-regular.woff2.license
  server/public/index.go.html
  server/public/intro.css
  server/public/offen-icon-black.svg.license
  server/public/robots.txt.license
  server/public/tachyons.min.css
  server/refresh.yml
  test-site/README.md
  vault/README.md
  vault/index.html
Labels: chore

#389 Improve color scheme to be more accessible, update banner content
  auditorium/src/views/components/_shared/account-picker.js
  auditorium/src/views/components/_shared/labeled-input.js
  auditorium/src/views/components/_shared/share.js
  auditorium/src/views/components/_shared/with-layout.js
  auditorium/src/views/components/auditorium/basic-terms.js
  auditorium/src/views/components/auditorium/chart.js
  auditorium/src/views/components/auditorium/embed-code.js
  auditorium/src/views/components/auditorium/explainer-icon.js
  auditorium/src/views/components/auditorium/frequently-asked-questions.js
  auditorium/src/views/components/auditorium/go-settings.js
  auditorium/src/views/components/auditorium/header.js
  auditorium/src/views/components/auditorium/metrics.js
  auditorium/src/views/components/auditorium/privacy.js
  auditorium/src/views/components/auditorium/range-selector.js
  auditorium/src/views/components/auditorium/retention-chart.js
  auditorium/src/views/components/auditorium/retire-account.js
  auditorium/src/views/components/auditorium/share.js
  auditorium/src/views/components/auditorium/tables.js
  auditorium/src/views/components/auditorium/url-tables.js
  auditorium/src/views/components/console/change-email.js
  auditorium/src/views/components/console/create-account.js
  auditorium/src/views/components/console/header.js
  auditorium/src/views/components/forgot-password/form.js
  auditorium/src/views/components/index/consent-status-display.js
  auditorium/src/views/components/index/header-card.js
  auditorium/src/views/components/index/main-card.js
  auditorium/src/views/components/login/form.js
  auditorium/src/views/components/reset-password/form.js
  server/public/index.go.html
  vault/src/user-consent.js
Labels: feature

#392 Merge docs site and integrate into release flow
  .circleci/config.yml
  .gitignore
  .reuse/dep5
  Dockerfile.ruby
  Makefile
  README.md
  build/Dockerfile.docs
  docker-compose.docs.yml
  docs/.gitignore
  docs/404.html
  docs/Gemfile
  docs/Gemfile.lock
  docs/README.md
  docs/_config.yml
  docs/_includes/head_custom.html
  docs/_includes/title.html
  docs/_layouts/default.html
  docs/_layouts/page.html
  docs/_override.yml
  docs/_sass/custom/custom.scss
  docs/assets/fonts/roboto-v20-latin-700.ttf
  docs/assets/fonts/roboto-v20-latin-700.ttf.license
  docs/assets/fonts/roboto-v20-latin-700.woff
  docs/assets/fonts/roboto-v20-latin-700.woff.license
  docs/assets/fonts/roboto-v20-latin-700.woff2
  docs/assets/fonts/roboto-v20-latin-700.woff2.license
  docs/assets/fonts/roboto-v20-latin-regular.ttf
  docs/assets/fonts/roboto-v20-latin-regular.ttf.license
  docs/assets/fonts/roboto-v20-latin-regular.woff
  docs/assets/fonts/roboto-v20-latin-regular.woff.license
  docs/assets/fonts/roboto-v20-latin-regular.woff2
  docs/assets/fonts/roboto-v20-latin-regular.woff2.license
  docs/assets/images/offen-icon-black.svg
  docs/assets/images/offen-icon-black.svg.license
  docs/assets/js/search-data.json
  docs/assets/js/search-data.json.license
  docs/docs/developing-offen/developing-offen.md
  docs/docs/developing-offen/generating-usage-data.md
  docs/docs/developing-offen/programming-languages.md
  docs/docs/developing-offen/required-tools.md
  docs/docs/developing-offen/setup.md
  docs/docs/developing-offen/understanding-architecture.md
  docs/docs/developing-offen/understanding-cryptography.md
  docs/docs/developing-offen/understanding-development-setup.md
  docs/docs/running-offen/configuring-the-application.md
  docs/docs/running-offen/downloads-distributions.md
  docs/docs/running-offen/embedding-the-script.md
  docs/docs/running-offen/installation-requirements.md
  docs/docs/running-offen/metrics-explained.md
  docs/docs/running-offen/running-offen.md
  docs/docs/running-offen/test-drive.md
  docs/docs/running-offen/tutorials/configuring-deploying-offen-docker.md
  docs/docs/running-offen/tutorials/configuring-deploying-offen-heroku.md
  docs/docs/running-offen/tutorials/configuring-deploying-offen-ubuntu.md
  docs/docs/running-offen/tutorials/tutorials.md
  docs/docs/running-offen/using-the-command.md
  docs/index.md
  docs/robots.txt
  nginx.docs.conf
Labels: feature

#394 Explicitly use TEXT fields for large data in MySQL
  server/persistence/relational/models.go
  server/persistence/relational/relational.go
Labels: fix

#395 Run integration tests against all supported database types
  .circleci/config.yml
  docs/docs/running-offen/configuring-the-application.md
Labels: chore

#396 Update index text in docs site
  docs/index.md
Labels: docs

#403 Properly implement in memory fallback key storage
  vault/src/queries.js
Labels: fix

#402 Actively discourage the use of a reverse proxy in the docs
  docs/docs/running-offen/installation-requirements.md
Labels: docs

#404 Add Hacker News to referrer buckets
  vault/src/buckets.js
  vault/src/buckets.test.js
Labels: feature

#401 Tighten event validation and parsing
  vault/src/queries.js
  vault/src/queries.test.js
Labels: fix

#405 Establish password policy
  .circleci/config.yml
  auditorium/gulpfile.js
  auditorium/package-lock.json
  auditorium/package.json
  auditorium/src/views/components/_shared/new-password-input.js
  auditorium/src/views/components/console/change-password.js
  auditorium/src/views/components/join/form.js
  auditorium/src/views/components/reset-password/form.js
  auditorium/src/views/components/setup/form.js
  docker-compose.integration.yml
  server/Makefile
  server/bootstrap.yml
  server/cmd/offen/cmddemo.go
  server/cmd/offen/cmdsetup.go
  server/keys/password.go
  server/keys/password_test.go
  server/persistence/bootstrap.go
  server/persistence/login.go
  server/persistence/management.go
  server/persistence/management_test.go
Labels: feature

#406 Harden server by applying selective rate limits to routes
  server/go.mod
  server/go.sum
  server/ratelimiter/ratelimiter.go
  server/ratelimiter/ratelimiter_test.go
  server/router/accounts.go
  server/router/events.go
  server/router/exchange.go
  server/router/login.go
  server/router/management.go
  server/router/router.go
  server/router/setup.go
Labels: feature

#407 Add more docs and hints on subdomain setup
  auditorium/src/views/components/auditorium/embed-code.js
  docs/docs/running-offen/embedding-the-script.md
  docs/docs/running-offen/metrics-explained.md
  docs/docs/running-offen/setting-up-using-subdomains.md
  docs/docs/running-offen/test-drive.md
Labels: docs

#409 Do not apply rate limiting rules when running behind a reverse proxy
  server/ratelimiter/ratelimiter.go
  server/router/router.go
Labels: chore

#408 Alpha Release 10
  .circleci/config.yml
  .reuse/dep5
  AUTHORS
  auditorium/gulpfile.js
  auditorium/package-lock.json
  auditorium/package.json
  auditorium/src/views/components/_shared/new-password-input.js
  auditorium/src/views/components/auditorium/embed-code.js
  auditorium/src/views/components/console/change-password.js
  auditorium/src/views/components/join/form.js
  auditorium/src/views/components/reset-password/form.js
  auditorium/src/views/components/setup/form.js
  banner.txt
  build/Dockerfile.build
  docker-compose.integration.yml
  docs/docs/running-offen/downloads-distributions.md
  docs/docs/running-offen/embedding-the-script.md
  docs/docs/running-offen/installation-requirements.md
  docs/docs/running-offen/metrics-explained.md
  docs/docs/running-offen/setting-up-using-subdomains.md
  docs/docs/running-offen/test-drive.md
  docs/docs/running-offen/tutorials/configuring-deploying-offen-ubuntu.md
  docs/index.md
  server/Makefile
  server/bootstrap.yml
  server/cmd/offen/cmddemo.go
  server/cmd/offen/cmdsetup.go
  server/go.mod
  server/go.sum
  server/keys/password.go
  server/keys/password_test.go
  server/persistence/bootstrap.go
  server/persistence/login.go
  server/persistence/management.go
  server/persistence/management_test.go
  server/ratelimiter/ratelimiter.go
  server/ratelimiter/ratelimiter_test.go
  server/router/accounts.go
  server/router/events.go
  server/router/exchange.go
  server/router/login.go
  server/router/management.go
  server/router/router.go
  server/router/setup.go
  server/router/static.go
  vault/package-lock.json
  vault/package.json
  vault/src/buckets.js
  vault/src/buckets.test.js
  vault/src/queries.js
  vault/src/queries.test.js
Labels: release

#410 Use common log format for access logs
  server/router/router.go
Labels: feature

#411 Add doc on how to monitor an instance
  docs/docs/running-offen/metrics-explained.md
  docs/docs/running-offen/monitoring-offen.md
  docs/docs/running-offen/test-drive.md
Labels: docs
